---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: ''
- name: permalink
  label: Permalink
  type: text
  hidden: false
  default: ''
pages:
- _pages/jedalny-listok.html
- _pages/o-nas.md
- _pages/kontakt.html
